testImplications <- function( covariance.matrix, sample.size ){
  library(ggm)
  tst <- function(i){ pcor.test( pcor(i,covariance.matrix), length(i)-2, sample.size )$pvalue }
  tos <- function(i){ paste(i,collapse=" ") }
  implications <- list(c("vote_count_community","vote_avg_community","movie_popularity"),
                       c("vote_count_community","vote_count_critics","movie_popularity"),
                       c("vote_count_community","vote_avg_critics","movie_popularity"),
                       c("vote_count_community","revenue","movie_popularity"),
                       c("vote_count_community","budget","major","genre","cast_popularity"),
                       c("vote_count_community","budget","genre","us","cast_popularity"),
                       c("vote_count_community","budget","movie_popularity"),
                       c("vote_count_community","genre","movie_popularity"),
                       c("vote_count_community","major","us","genre","budget"),
                       c("vote_count_community","major","cast_popularity","genre","us"),
                       c("vote_count_community","major","movie_popularity"),
                       c("vote_count_community","us","movie_popularity"),
                       c("vote_count_community","cast_popularity","movie_popularity"),
                       c("vote_avg_community","vote_count_critics","movie_popularity"),
                       c("vote_avg_community","vote_avg_critics"),
                       c("vote_avg_community","revenue","movie_popularity"),
                       c("vote_avg_community","budget"),
                       c("vote_avg_community","genre"),
                       c("vote_avg_community","major"),
                       c("vote_avg_community","us"),
                       c("vote_avg_community","cast_popularity"),
                       c("vote_count_critics","vote_avg_critics","movie_popularity"),
                       c("vote_count_critics","revenue","movie_popularity"),
                       c("vote_count_critics","budget","major","genre","cast_popularity"),
                       c("vote_count_critics","budget","genre","us","cast_popularity"),
                       c("vote_count_critics","budget","movie_popularity"),
                       c("vote_count_critics","genre","movie_popularity"),
                       c("vote_count_critics","major","us","genre","budget"),
                       c("vote_count_critics","major","cast_popularity","genre","us"),
                       c("vote_count_critics","major","movie_popularity"),
                       c("vote_count_critics","us","movie_popularity"),
                       c("vote_count_critics","cast_popularity","movie_popularity"),
                       c("vote_avg_critics","revenue","movie_popularity"),
                       c("vote_avg_critics","budget"),
                       c("vote_avg_critics","genre"),
                       c("vote_avg_critics","major"),
                       c("vote_avg_critics","us"),
                       c("vote_avg_critics","cast_popularity"),
                       c("revenue","budget","major","genre","cast_popularity"),
                       c("revenue","budget","genre","us","cast_popularity"),
                       c("revenue","budget","movie_popularity"),
                       c("revenue","genre","movie_popularity"),
                       c("revenue","major","us","genre","budget"),
                       c("revenue","major","cast_popularity","genre","us"),
                       c("revenue","major","movie_popularity"),
                       c("revenue","us","movie_popularity"),
                       c("revenue","cast_popularity","movie_popularity"),
                       c("budget","us","major"),
                       c("budget","movie_popularity","genre","cast_popularity","us"),
                       c("budget","movie_popularity","genre","cast_popularity","major"),
                       c("genre","us","major"),
                       c("genre","cast_popularity","budget"),
                       c("major","movie_popularity","genre","cast_popularity","us"),
                       c("major","movie_popularity","genre","us","budget"),
                       c("major","cast_popularity","budget"),
                       c("us","cast_popularity","budget"),
                       c("us","cast_popularity","major"))
  data.frame( implication=unlist(lapply(implications,tos)),
              pvalue=unlist( lapply( implications, tst ) ) )
  
}